test echo

diff --git a/Jenkinsfile_CNP b/Jenkinsfile_CNP
--- a/Jenkinsfile_CNP
+++ b/Jenkinsfile_CNP
@@ -97,24 +97,20 @@ withPipeline(type, product, component) {
         }
 
         stage('Auto-Commit Suppressions') {
+            def targetBranch = 'test-fix-workflow-suppression'
             sh """
-                git remote set-url origin https://dinesh1patel:testing123!@github.com/hmcts/ccd-user-profile-api.git
+                git fetch origin
 
-                git checkout test-fix-workflow-suppression
-
-                git add .
-                git diff-index --quiet HEAD || git commit -m "Auto commit to develop branch"
-                git push origin test-fix-workflow-suppression
+                if git rev-parse --verify origin/${targetBranch} >/dev/null 2>&1; then
+                    git checkout -B ${targetBranch} origin/${targetBranch}
+                    git add .
+                    git diff-index --quiet HEAD || git commit -m "Auto commit to develop branch"
+                    git push origin test-fix-workflow-suppression
+                else
+                    echo "Branch '${targetBranch}' not found on remote"
+                    exit 1
+                fi
             """
-            script {
-                gitAutoCommit(
-                    commitMessage: 'Suppressing CVE - Actions',
-                    branch: 'test-fix-workflow-suppression',
-                    credentialsId: 'git-auto-commit',
-                    userName: 'jenkins',
-                    userEmail: 'jenkins@example.com'
-                )
-            }
         }
     }
 
